{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.namespace }}-{{ .Values.prefix }}-kc
  name: {{ .Values.namespace }}-{{ .Values.prefix }}-kc-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.namespace }}-{{ .Values.prefix }}-kc
{{- end }}