{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.namespace }}-{{ .Values.prefix }}-webhook-handler
  name: {{ .Values.namespace }}-{{ .Values.prefix }}-webhook-handler
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.namespace }}-{{ .Values.prefix }}-webhook-handler
  template:
    metadata:
      labels:
        app: {{ .Values.namespace }}-{{ .Values.prefix }}-webhook-handler
    spec:
      imagePullSecrets:
        - name: {{ .Values.api.imagePullSecret }}
      containers:
        - command:
            - ./app/bin/igrant-api
            - start-webhook-api
            - --config
            - config-production.json
          image: {{ .Values.api.image }}
          imagePullPolicy: Always
          name: {{ .Values.namespace }}-{{ .Values.prefix }}-webhook-handler
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/l3-igrant/api/config
              name: config-volume
          securityContext:
            {{- if .Values.securityContext }}
              {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          resources:
            {{- if .Values.resources }}
              {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ .Values.namespace }}-{{ .Values.prefix }}-api-config
          name: config-volume
{{- end }}