{{- if .Values.organisationWallet.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.namespace }}-{{ .Values.prefix }}-config-ow
  name: {{ .Values.namespace }}-{{ .Values.prefix }}-config-ow-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.namespace }}-{{ .Values.prefix }}-config-ow
  type: ClusterIP
{{- end }}