{{- if .Values.vaultFacade.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namespace }}-{{ .Values.prefix }}-vault-facade-secret
  namespace: {{ .Values.namespace }}
data:
  {{- if eq (default "vault" .Values.vaultFacade.appMode) "vault" }}
  VAULT_ADDR: {{ .Values.vaultFacade.vault.addr | b64enc }}
  VAULT_USER: {{ .Values.vaultFacade.vault.user | b64enc }}
  VAULT_PASSWORD: {{ .Values.vaultFacade.vault.password | b64enc }}
  {{- else if eq .Values.vaultFacade.appMode "mongo" }}
  MONGO_HOSTS: {{ printf "%s-%s-mongo-svc" .Values.namespace (default "" .Values.prefix) | b64enc }}
  MONGO_DATABASE: {{ .Values.mongo.database | b64enc }}
  MONGO_USERNAME: {{ .Values.mongo.username | b64enc }}
  MONGO_PASSWORD: {{ .Values.mongo.password | b64enc }}
  {{- end }}
{{- end }}
