{{- if .Values.vaultFacade.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namespace }}-{{ .Values.prefix }}-vault-facade-secret
  namespace: {{ .Values.namespace }}
data:
  VAULT_ADDR: {{ .Values.vaultFacade.vaultAddr | b64enc }}
  VAULT_USER: {{ .Values.vaultFacade.vaultUser | b64enc }}
  VAULT_PASSWORD: {{ .Values.vaultFacade.vaultPassword | b64enc }}
{{- end }}
