{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.namespace }}-{{ .Values.prefix }}-api
  name: {{ .Values.namespace }}-{{ .Values.prefix }}-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.namespace }}-{{ .Values.prefix }}-api
  template:
    metadata:
      labels:
        app: {{ .Values.namespace }}-{{ .Values.prefix }}-api
    spec:
      {{- if .Values.api.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.api.imagePullSecret }}
      {{- end }}
      containers:
      - image: {{ .Values.api.image }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.namespace }}-{{ .Values.prefix }}-api
        {{- if .Values.api.configuration.env }}
        env:
          {{- toYaml .Values.api.configuration.env | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/l3-igrant/api/config
          name: config-volume
        resources:
          {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      securityContext:
        {{- if .Values.securityContext }}
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Values.namespace }}-{{ .Values.prefix }}-api-config
        name: config-volume
{{- end }}